--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/ImageToParticle
branches:
- master
projects:
  ImageToParticle:
    path: ""
    libs:
      - src: sky-min/FormLib/FormLib
        version: ^1.1.3
...
