name: ImageParticle
main: skymin\ImageParticle\Loader
src-namespace-prefix: skymin\ImageParticle
version: 2.1.1
author: skymin
api:
  - 4.11.0
  - 5.0.0

permissions:
  imageparticle.op:
    default: op
